version: '3'

services:
  airflow-webserver:
    image: apache/airflow:2.7.1
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=<YOUR_FERNET_KEY>
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./component:/opt/airflow/component  # Mount your ETL components
      - ./config.yaml:/opt/airflow/config.yaml  # Mount your config file
      - ./schema.yaml:/opt/airflow/schema.yaml  # Mount your schema file
      - ./datasets:/opt/airflow/datasets  # Mount datasets directory
      - ./logger:/opt/airflow/logger.py  # Mount logger directory
      
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init
      - postgres

  airflow-scheduler:
    image: apache/airflow:2.7.1
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=""
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - airflow-init
      - postgres

  airflow-init:
    image: apache/airflow:2.7.1
    command: "airflow db init"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./component:/opt/airflow/component  # Mount your ETL components
      - ./config.yaml:/opt/airflow/config.yaml  # Mount your config file
      - ./schema.yaml:/opt/airflow/schema.yaml  # Mount your schema file
      - ./datasets:/opt/airflow/datasets  # Mount datasets directory
      - ./logger:/opt/airflow/logger.py  # Mount logger directory
      
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=""

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
