COLUMNS:
  sensor : object 
  creation_time: datetime64[ns]
  R_Voltage: float64
  Y_Voltage: float64
  B_Voltage: float64
  R_Current: float64
  Y_Current: float64
  B_Current: float64
  kWh : float64  